title: Ridho Nugroho # your name (or website title) here
logo: "/images/pp.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  I am a 4th-semester Informatics Engineering student with a strong passion for Artificial Intelligence and Data Science. My academic journey is driven by curiosity to explore how data and intelligent systems can create impactful solutions for real-world problems. I enjoy experimenting with machine learning models, data preprocessing, and statistical analysis using Python and tools like RapidMiner, Google Colab, and TensorFlow. 
  <br><br>
  Through hands-on projects, I’ve built a solid foundation in developing predictive models, data visualizations, and AI-powered systems. I’m always eager to learn and improve—whether through research, online courses, or collaborative projects. My goal is to contribute to meaningful innovations in AI and Data Science that not only solve problems but also shape a smarter future.
  <br><br>
  <a href="https://www.linkedin.com/in/ridho-nugroho-a249b8361/">View My LinkedIn Profile</a> 
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
